swagger: "2.0"
info:
  title: Terraformado 1.0
  version: 1.0.0
paths:
  /hello:
    get:
      produces:
        - application/json
      responses:
        200:
          description: A successful response
          schema:
            type: object
            properties:
              message:
                type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:sa-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:sa-east-1:724772056724:function:gtw-teste/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
